### ISSUE TITLE
create_user throwing error

### ISSUE THREAD

**Issue by aanderse** [usit-gd/zabbix-cli#110]
I'm seeing an error when I try to use `create_user`: 
```
$ zabbix-cli -C "create_user 'test' 'Test' 'Person' '' '1' '0' '86400' 'Guests'"

[Error]: Problems getting usergroupID - Could not find usergroupID for: All-users
```

Relevant environment details:
```
Welcome to the Zabbix command-line interface (v2.1.1)
Connected to server - (v4.2.3)
```

Maybe I'm using the command incorrectly? Any help would be appreciated.

**Comment by paalbra** [comment]
`create_user` will try to add a user to all usergroups set in `default_create_user_usergroup` in the config. The default value for this is `All-users` which is a usergroup I assume that you don't have.

**Comment by aanderse** [comment]
@paalbra ah even if I explicitly set the group! Thank you so much for the explanation, and your work on this great piece of software!
