### ISSUE TITLE
Claims to have a problem removing a host, while it actually succeeds

### ISSUE THREAD

**Issue by volter** [usit-gd/zabbix-cli#22]
I created a host "blub" in the frontend (3.0) and then try to remove it via zabbix-cli 1.6.1. The host is removed, but there's an error message too, that is confusing.

```
[zabbix-cli zabbix@Office]$  remove_host blub

[Done]: Hosts (blub) with IDs: 10468 removed



[Error]: Problems removing hosts (blub)

```

**Comment by volter** [comment]
Perhaps related to #24

**Comment by usit-gd** [comment]
Hello Volter

Thank you for the report. 

This is a confirmed bug and will be fixed in the next release.
