### ISSUE TITLE
Host can not be created if the group set in default_hostgroup does not exist

### ISSUE THREAD

**Issue by volter** [usit-gd/zabbix-cli#24]
Even if you specify a group upon host creation, the existence of the default_group is still expected and the operation will fail if it doesn't exist.

**Comment by usit-gd** [comment]
We still want to have the opportunity of defining a default hostgroup where the new host will get registered even if we define our own hostgroups in the create_host command.

I agree that not everybody needs this functionality. The solution we can implement is:

* Use the default_hostgroup value when creating a new host only if it has a value defined in the configuration file and this value exists in Zabbix.

If default_hostgroup doesn't exist or it is not defined, the create_host command will exit with an error if we do not provide an existing hostgroup upon host creation.

**Comment by volter** [comment]
That sounds good!
