### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by invin12** [usit-gd/zabbix-cli#29]
It would be better to see exit code not zero when some errors in execution. It's very helpful in shell-scripting..

But exit-code is always zero now
tester@zabbix-test:/usr/lib/zabbix/externalscripts# zabbix-cli -C "add_host_to_hostgroup test test"
[Error]: Problems adding hosts test () to groups test ()
root@zabbix-test:/usr/lib/zabbix/externalscripts# echo $?
0

**Comment by usit-gd** [comment]
Thanks for the feedback

+1 . Exit codes should not be 0 after an error.
