### ISSUE TITLE
Non-interactive export_configuration

### ISSUE THREAD

**Issue by invin12** [usit-gd/zabbix-cli#30]
I think it would be good, if it would be possible to make non-interactive export_configuration. 
As a cronjob, it will be regular backup solution of zabbix configuration.

**Comment by usit-gd** [comment]
This should work without problems. 
What is the problem, do you get any errors?

**Comment by invin12** [comment]
root@zabbix-test:~# zabbix-cli -C "export_configuration"
--------------------------------------------------------
# Directory [/root/zabbix_exports]: 
# Object type [#all#]: 
# Object name [#all#]: 
--------------------------------------------------------

Is it possible to make export without selecting Directory, Object type and Object name? Cron job don't work without selection.

**Comment by usit-gd** [comment]
You can define your cronjob with parameters. e.g.
01 01 * * * root /usr/bin/zabbix-cli -C"export_configuration '' '' '' "

without problems. If you use '' '' '' (empty parameters) the server will use the default values.

Check the documentation:
https://github.com/usit-gd/zabbix-cli/blob/master/docs/manual.rst#zabbix-cli-shell
