### ISSUE TITLE
Dont import configuration. These files would be imported with dry run: OFF

### ISSUE THREAD

**Issue by patsevanton** [usit-gd/zabbix-cli#33]
[root@zabbix-server .zabbix-cli]# zabbix-cli --command "import_configuration zbx-linux-envmon.xml"
 
 Dry run: ON
 These files would be imported with dry run: OFF
 
[Done]: Total files Imported [0] / Not imported [0]

#############################################################
 Welcome to the Zabbix command-line interface (v.1.6.0)
 #############################################################
Type help or \? to list commands.

Zabbix 3.0.7

[root@zabbix-server .zabbix-cli]# cat zabbix-cli.conf | grep -v ";" | grep -v "^$"
[zabbix_api]
zabbix_api_url=http://localhost/zabbix
[zabbix_config]
default_hostgroup=All-hosts
default_admin_usergroup=Zabbix-root
default_create_user_usergroup=All-users
default_notification_users_usergroup=All-notification-users
include_timestamp_export_filename=ON
use_colors=ON
use_auth_token_file=OFF
[logging]
logging=OFF
log_level=DEBUG
log_file=/root/.zabbix-cli/zabbix-cli.log

**Comment by usit-gd** [comment]
Hello

This the expected behavior for this command if you do not define "dry run":OFF.
Ref: https://github.com/usit-gd/zabbix-cli/blob/master/docs/manual.rst#import-configuration

Try:
zabbix-cli --command "import_configuration zbx-linux-envmon.xml 0"

**Comment by patsevanton** [comment]
Thanks
