### ISSUE TITLE
RPM build errors: error: can't copy 'etc/zabbix-cli.conf': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by patsevanton** [usit-gd/zabbix-cli#39]
> [vagrant@etcd 9]$ git clone https://github.com/usit-gd/zabbix-cli.git
> Cloning into 'zabbix-cli'...
> remote: Counting objects: 958, done.
> remote: Compressing objects: 100% (31/31), done.
> remote: Total 958 (delta 16), reused 0 (delta 0), pack-reused 927
> Receiving objects: 100% (958/958), 471.30 KiB | 281.00 KiB/s, done.
> Resolving deltas: 100% (599/599), done.
> [vagrant@etcd 9]$ cd zabbix-cli/
> [vagrant@etcd zabbix-cli]$ python setup.py bdist --formats=rpm
> running bdist
> running bdist_rpm
> running egg_info
> creating zabbix_cli.egg-info
> writing requirements to zabbix_cli.egg-info/requires.txt
> writing zabbix_cli.egg-info/PKG-INFO
> writing top-level names to zabbix_cli.egg-info/top_level.txt
> writing dependency_links to zabbix_cli.egg-info/dependency_links.txt
> writing manifest file 'zabbix_cli.egg-info/SOURCES.txt'
> reading manifest file 'zabbix_cli.egg-info/SOURCES.txt'
> writing manifest file 'zabbix_cli.egg-info/SOURCES.txt'
> creating build
> creating build/bdist.linux-x86_64
> creating build/bdist.linux-x86_64/rpm
> creating build/bdist.linux-x86_64/rpm/SOURCES
> creating build/bdist.linux-x86_64/rpm/SPECS
> creating build/bdist.linux-x86_64/rpm/BUILD
> creating build/bdist.linux-x86_64/rpm/RPMS
> creating build/bdist.linux-x86_64/rpm/SRPMS
> writing 'build/bdist.linux-x86_64/rpm/SPECS/zabbix_cli.spec'
> running sdist
> warning: sdist: standard file not found: should have one of README, README.rst, README.txt
> 
> running check
> creating zabbix_cli-1.6.1
> creating zabbix_cli-1.6.1/bin
> creating zabbix_cli-1.6.1/zabbix_cli
> creating zabbix_cli-1.6.1/zabbix_cli.egg-info
> making hard links in zabbix_cli-1.6.1...
> hard linking setup.py -> zabbix_cli-1.6.1
> hard linking bin/zabbix-cli -> zabbix_cli-1.6.1/bin
> hard linking bin/zabbix-cli-bulk-execution -> zabbix_cli-1.6.1/bin
> hard linking bin/zabbix-cli-init -> zabbix_cli-1.6.1/bin
> hard linking zabbix_cli/__init__.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli/cli.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli/config.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli/logs.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli/prettytable.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli/pyzabbix.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli/version.py -> zabbix_cli-1.6.1/zabbix_cli
> hard linking zabbix_cli.egg-info/PKG-INFO -> zabbix_cli-1.6.1/zabbix_cli.egg-info
> hard linking zabbix_cli.egg-info/SOURCES.txt -> zabbix_cli-1.6.1/zabbix_cli.egg-info
> hard linking zabbix_cli.egg-info/dependency_links.txt -> zabbix_cli-1.6.1/zabbix_cli.egg-info
> hard linking zabbix_cli.egg-info/requires.txt -> zabbix_cli-1.6.1/zabbix_cli.egg-info
> hard linking zabbix_cli.egg-info/top_level.txt -> zabbix_cli-1.6.1/zabbix_cli.egg-info
> Writing zabbix_cli-1.6.1/setup.cfg
> creating dist
> Creating tar archive
> removing 'zabbix_cli-1.6.1' (and everything under it)
> copying dist/zabbix_cli-1.6.1.tar.gz -> build/bdist.linux-x86_64/rpm/SOURCES
> building RPMs
> rpmbuild -ba --define _topdir /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm --clean build/bdist.linux-x86_64/rpm/SPECS/zabbix_cli.spec
> Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.npFtOf
> + umask 022
> + cd /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILD
> + cd /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILD
> + rm -rf zabbix_cli-1.6.1
> + /usr/bin/tar -xvvf -
> + /usr/bin/gzip -dc /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/SOURCES/zabbix_cli-1.6.1.tar.gz
> drwxrwxr-x vagrant/vagrant   0 2017-03-30 05:31 zabbix_cli-1.6.1/
> drwxrwxr-x vagrant/vagrant   0 2017-03-30 05:31 zabbix_cli-1.6.1/bin/
> -rwxrwxr-x vagrant/vagrant 11440 2017-03-30 05:31 zabbix_cli-1.6.1/bin/zabbix-cli
> -rwxrwxr-x vagrant/vagrant  4740 2017-03-30 05:31 zabbix_cli-1.6.1/bin/zabbix-cli-bulk-execution
> -rwxrwxr-x vagrant/vagrant  3369 2017-03-30 05:31 zabbix_cli-1.6.1/bin/zabbix-cli-init
> drwxrwxr-x vagrant/vagrant     0 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/
> -rw-rw-r-- vagrant/vagrant     0 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/__init__.py
> -rw-rw-r-- vagrant/vagrant 259412 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/cli.py
> -rw-rw-r-- vagrant/vagrant   6697 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/config.py
> -rw-rw-r-- vagrant/vagrant   1944 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/logs.py
> -rw-rw-r-- vagrant/vagrant  54204 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/prettytable.py
> -rw-rw-r-- vagrant/vagrant   7276 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/pyzabbix.py
> -rw-rw-r-- vagrant/vagrant     44 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli/version.py
> drwxrwxr-x vagrant/vagrant      0 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli.egg-info/
> -rw-rw-r-- vagrant/vagrant    692 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli.egg-info/PKG-INFO
> -rw-rw-r-- vagrant/vagrant    394 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli.egg-info/SOURCES.txt
> -rw-rw-r-- vagrant/vagrant      1 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli.egg-info/dependency_links.txt
> -rw-rw-r-- vagrant/vagrant     17 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli.egg-info/requires.txt
> -rw-rw-r-- vagrant/vagrant     11 2017-03-30 05:31 zabbix_cli-1.6.1/zabbix_cli.egg-info/top_level.txt
> -rwxrwxr-x vagrant/vagrant   2465 2017-03-30 05:31 zabbix_cli-1.6.1/setup.py
> -rw-rw-r-- vagrant/vagrant    692 2017-03-30 05:31 zabbix_cli-1.6.1/PKG-INFO
> -rw-rw-r-- vagrant/vagrant     59 2017-03-30 05:31 zabbix_cli-1.6.1/setup.cfg
> + STATUS=0
> + '[' 0 -ne 0 ']'
> + cd zabbix_cli-1.6.1
> + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
> + exit 0
> Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.DvP7MP
> + umask 022
> + cd /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILD
> + cd zabbix_cli-1.6.1
> + python setup.py build
> running build
> running build_py
> creating build
> creating build/lib
> creating build/lib/zabbix_cli
> copying zabbix_cli/__init__.py -> build/lib/zabbix_cli
> copying zabbix_cli/cli.py -> build/lib/zabbix_cli
> copying zabbix_cli/config.py -> build/lib/zabbix_cli
> copying zabbix_cli/logs.py -> build/lib/zabbix_cli
> copying zabbix_cli/prettytable.py -> build/lib/zabbix_cli
> copying zabbix_cli/pyzabbix.py -> build/lib/zabbix_cli
> copying zabbix_cli/version.py -> build/lib/zabbix_cli
> running build_scripts
> creating build/scripts-2.7
> copying and adjusting bin/zabbix-cli -> build/scripts-2.7
> copying and adjusting bin/zabbix-cli-bulk-execution -> build/scripts-2.7
> copying and adjusting bin/zabbix-cli-init -> build/scripts-2.7
> changing mode of build/scripts-2.7/zabbix-cli from 644 to 755
> changing mode of build/scripts-2.7/zabbix-cli-bulk-execution from 644 to 755
> changing mode of build/scripts-2.7/zabbix-cli-init from 644 to 755
> + exit 0
> Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.iNDm0p
> + umask 022
> + cd /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILD
> + '[' /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64 '!=' / ']'
> + rm -rf /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64
> ++ dirname /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64
> + mkdir -p /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT
> + mkdir /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64
> + cd zabbix_cli-1.6.1
> + python setup.py install --single-version-externally-managed -O1 --root=/home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64 --record=INSTALLED_FILES
> running install
> running build
> running build_py
> running build_scripts
> running install_lib
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/__init__.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/cli.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/config.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/logs.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/prettytable.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/pyzabbix.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> copying build/lib/zabbix_cli/version.py -> /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/__init__.py to __init__.pyc
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/cli.py to cli.pyc
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/config.py to config.pyc
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/logs.py to logs.pyc
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/prettytable.py to prettytable.pyc
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/pyzabbix.py to pyzabbix.pyc
> byte-compiling /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/lib/python2.7/site-packages/zabbix_cli/version.py to version.pyc
> writing byte-compilation script '/tmp/tmp_ZFkRy.py'
> /usr/bin/python -O /tmp/tmp_ZFkRy.py
> removing /tmp/tmp_ZFkRy.py
> running install_data
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/share
> creating /home/vagrant/9/zabbix-cli/build/bdist.linux-x86_64/rpm/BUILDROOT/zabbix_cli-1.6.1-1.x86_64/usr/share/zabbix-cli
> error: can't copy 'etc/zabbix-cli.conf': doesn't exist or not a regular file
> error: Bad exit status from /var/tmp/rpm-tmp.iNDm0p (%install)
> 
> 
> RPM build errors:
>     Bad exit status from /var/tmp/rpm-tmp.iNDm0p (%install)
> error: command 'rpmbuild' failed with exit status 1
> [vagrant@etcd zabbix-cli]$ cat /etc/redhat-release
> CentOS Linux release 7.3.1611 (Core)
>

**Comment by cyfive** [comment]
Create MANIFEST.in in project root with content
`
[vagrant@localhost zabbix-cli]$ cat ./MANIFEST.in 
recursive-include etc *
`
Run build:
`
[vagrant@localhost zabbix-cli]$ python setup.py bdist_rpm
`

**Comment by paalbra** [comment]
There is a rpm spec file provided with the repo. Did you try to use the provided spec file?

**Comment by paalbra** [comment]
I'm closing this issue since it's very old. There is currently a new 2.0.1 release out that you might want to look into.
