### ISSUE TITLE
Having Trouble with  creating a  host group   using the cli.

### ISSUE THREAD

**Issue by farhandiwan** [usit-gd/zabbix-cli#40]
Can you give an example  on how the  input should be given via cli , a batch  will also be  good.
I need to add 200+ hosts in zabbix  and thought  of finding an semi automated way to  do that.

When I do host,.create  giving the hostname and other entries it fails.

**Comment by usit-gd** [comment]
Hei

From the command-line you can  this command:
# zabbix-cli -C "create_host test000001.example.net All-manual-hosts .+ 1"

Ref: https://github.com/usit-gd/zabbix-cli/blob/master/docs/manual.rst#create-host

In this section of the documentation, you have an example of how to run a bulk update via command-line and the -f parameter: https://github.com/usit-gd/zabbix-cli/blob/master/docs/manual.rst#zabbix-cli-shell

regards
