### ISSUE TITLE
Maintenance Type?

### ISSUE THREAD

**Issue by badbob001** [usit-gd/zabbix-cli#43]
When creating a maintenance plan, there is no option to specify the type: either 'with data collection' or 'no data collection'. So the plans are created with the default of 'with data collection', which is undesirable since triggers will still fire, despite being under maintenance.

**Comment by badbob001** [comment]
I've worked around the issue by editing ~/zabbix-cli/build/lib/zabbix_cli/cli.py and add ",maintenance_type=1,":

            result = self.zapi.maintenance.create(name=maintenance_name,
                                                  active_since=since,maintenance_type=1
                                                  active_till=till,
                                                  description=maintenance_description,
                                                  hostids=host_ids,
                                                  groupids=hostgroup_ids,
                                                  timeperiods=[
                                                      {
                                                          'start_date':since,
                                                          'period':sec,
                                                          'timeperiod_type':0
                                                      }
                                                  ])

And then run setup.py install.

When I tried adding the change to a new line, the app failed to run. Probably a issue with tabs.

**Comment by usit-gd** [comment]
Hei

You are right, this parameter is important to have. A patch has been commited and this will be available in the next release.
