### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by UncleCharlie** [usit-gd/zabbix-cli#44]
Hello,

We have encountered the following error message upon the installation of zabbix-cli on a SLES 11 SP3 server:

OTCge1-zabbix-master-241-10:/tmp # zabbix-cli
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-cli", line 4, in <module>
    __import__('pkg_resources').run_script('zabbix-cli==1.6.1', 'zabbix-cli')
  File "/usr/local/lib64/python2.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib64/python2.6/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib64/python2.6/site-packages/zabbix_cli-1.6.1-py2.6.egg/EGG-INFO/scripts/zabbix-cli", line 31, in <module>

  File "/usr/local/lib64/python2.6/site-packages/zabbix_cli-1.6.1-py2.6.egg/zabbix_cli/cli.py", line 2865
    interface_ip = '"ip":"' host + '",'
                               ^
SyntaxError: invalid syntax

We have followed the install instructions provided here, all the packages that were listed as needed are on the server, we have python version 2.6.8 and setuptools 35.0. The package was installed using the python installer with: python setup.py install. Could you please provide a hint as to where the problem may lie? thank you in advance!

**Comment by usit-gd** [comment]
Hello

It looks like you have installed the development version under the master branch. We are working in a new release and 'master' is not 100% stable at the moment.

If you want to install from the sources and not a rpm/deb package, you have to download a stable version from https://github.com/usit-gd/zabbix-cli/releases.

We will update the documentation to clarify this and avoid misunderstandings in the future.

Thanks for the report.
regards, 
Rafael Martinez Guerrero

**Comment by UncleCharlie** [comment]
Thanks a lot! I have downloaded the latest stable version and it runs perfectly! Thank you for the quick response!
