### ISSUE TITLE
acknowledge_events

### ISSUE THREAD

**Issue by UncleCharlie** [usit-gd/zabbix-cli#47]
Hello,

I would like to ask whether there is already a stable version, which has the acknowledge_events funciton in it. We currently use 1.6.1 and it doesn't yet contain this function. Thank you in advance!

**Comment by usit-gd** [comment]
Hei

The main branch is frozen and tested now and ready for a new release.

We have to run some last tests, tag the code (1.7.0), release the new version (1.7.0) and generate the rpm/deb packages.

We are creating an official RPM yum repo for zabbix-cli and we hope to have it in place next week. The official release will probably be done in week 22.

1.7.0 has two new commands to acknowledge events, check the manual https://github.com/usit-gd/zabbix-cli/blob/master/docs/manual.rst:

* acknowledge_event
* acknowledge_trigger_last_event
