### ISSUE TITLE
how to set ip address with create_host

### ISSUE THREAD

**Issue by garelp** [usit-gd/zabbix-cli#48]
Hello,

I'd like to know if it's possible to add a host and set the correct ip instead of using the DNS name with the create_host directive.

Thanks.

**Comment by rafaelma** [comment]
Hello

This has been fixed in https://github.com/usit-gd/zabbix-cli/issues/27 and it will be available in the next release 1.7.0.

We are working with this release and the rpm/deb packages and everything should be available to the public in a few days.

regards,
Rafael Martinez Guerrero

**Comment by garelp** [comment]
Excellent.

Thanks.
