### ISSUE TITLE
bulk insert not working

### ISSUE THREAD

**Issue by darrynv** [usit-gd/zabbix-cli#55]
Red Hat Enterprise Linux Server release 7.3 (Maipo)

zabbix_server (Zabbix) 3.4.1
Revision 71734 28 August 2017, compilation time: Aug 28 2017 10:10:28

Welcome to the Zabbix command-line interface (v.1.7.0)

Bulk load file : 
create_host host8 Linux-servers .+ 1
create_host host9 Linux-servers .+ 1
create_host host10 Linux-servers .+ 1
create_host host11 Linux-servers .+ 1
create_host host12 Linux-servers .+ 1
create_host host13 Linux-servers .+ 1
create_host host14 Linux-servers .+ 1
create_host host15 Linux-servers .+ 1
create_host host16 Linux-servers .+ 1

Error
[root@du0992mtmp0005 ~]# zabbix-cli -f hostlist.txt

Zabbix-CLI authentication

Username[root]: Admin
Password:
[OK] File [/root/hostlist.txt] exists. Bulk execution of commands defined in this file started.
[Warning]: This host (host8) already exists.
[Warning]: This host (host9) already exists.
[Done]: Host (host10) with ID: 10263 created

**Comment by paalbra** [comment]
I'm not sure what the problem was here, but it seems that it was fixed.
