### ISSUE TITLE
How do you install / setup ?

### ISSUE THREAD

**Issue by otheus** [usit-gd/zabbix-cli#6]
Especially if you're not root?

**Comment by rafaelma** [comment]
Hello

The setup.py file and RPMs need to install some files in the %{python2_sitelib}/ and /usr/bin directories and for this you need to be root.

On the other hand, zabbix-cli is just a python program and it doesn't need to be installed in 
%{python2_sitelib}/ and /usr/bin to work. 

The python files under bin/ and zabbix_cli/ in the source has some includes statements like _"import zabbix_cli.*"_ or _"from zabbix_cli.* import ...."_ This means that these files are looking for this import files under %{python2_sitelib}/zabbix_cli/

If you copy all files under bin/ and zabbix_cli/in the source to <your_directory> and modify all import statements from _"import zabbix_cli.xxxx" --> _"import xxxx"_ and _"from zabbix_cli.xxxx import yyyy"_  --> _"from xxxx import yyyy" things should work when you execute <your_directory>/zabbix-cli
