### ISSUE TITLE
Display proxy in "show_host"

### ISSUE THREAD

**Issue by safpsr** [usit-gd/zabbix-cli#65]
Hello,
Would it be possible to add a "show_host_proxy" command that would know which proxy a host is attached to?
Thanks a lot

**Comment by zebecasse** [comment]
Hello, i have the same question, the only way i found, is this : 
zabbix-cli -C "export_configuration \"/tmp\" \"hosts\" \"myserver\""
And go to : 
/tmp/hosts/*myserver*.xml to find my value

**Comment by paalbra** [comment]
The API provides the proxyid when you get a host. I suggest displaying the proxy name when using `show_host` rather than creating a new command.
