### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by leweafan** [usit-gd/zabbix-cli#67]
zabbix-cli supports json output but I can't use it with jq utility cause output not only json.
 
```
# zabbix-cli -C "show_hostgroups 'Linux servers'" -o json | jq .
parse error
```

**Comment by paalbra** [comment]
Are you able to provide the output from zabbix-cli?

**Comment by paalbra** [comment]
I'm closing this since we haven't received any feedback. You might have gotten a password prompt, but I'm not sure.
