### ISSUE TITLE
Hostgroup hosts

### ISSUE THREAD

**Issue by leweafan** [usit-gd/zabbix-cli#69]
I've been disappointed that zabbix-cli doesn't have command get_hostgroup_hosts (zabbix_tool) and show_host doesn't support hostgroup filter. Seems like json output and jq utility can help to solve it. But json output is more than json. May be there is another way?

**Comment by paalbra** [comment]
I'm not familiar with zabbix_tool, but I guess you could do this the other way around by using `show_hostgroup`. That command will show to the hosts in the hostgroup.

And yes, if you get the password prompt it will be output to stdout. If you use a access token and json output jq should work for you.

This one works for me with v1.7.0:

`zabbix-cli -C "show_hostgroup Some-hostgroup" -o json | jq '."0".hosts'`

Does this answer your questions?

**Comment by paalbra** [comment]
I'm closing this due to lacking feedback
