### ISSUE TITLE
Add basic auth support

### ISSUE THREAD

**Issue by thelan** [usit-gd/zabbix-cli#7]
Hello,

Actually this works by adding the user login and password to the "zabbix_api_url" in the config file as in the .zabbix-cli_auth.

Will you plan to read the credentials from the .zabbix-cli_auth file to generate the proper Auhorization header?

Regards,

**Comment by usit-gd** [comment]
We need to install a zabbix installation with basic auth before we can implement this. We do not have time for this before 1.7.0.

**Comment by arrfab** [comment]
I admit that I just tested also zabbix-cli against a zabbix server configured for basic_auth, but the apache module itself using openid, and that it doesn't work . (as expected)

**Comment by paalbra** [comment]
HTTP basic auth in the API has been broken from Zabbix 3.4 to 4.0. This is an issue in Zabbix itself and not in zabbix-cli or pyzabbix.

I'm closing this issue. Further discussion can continue in #80
