### ISSUE TITLE
show_maintenance_periods

### ISSUE THREAD

**Issue by bundaburg** [usit-gd/zabbix-cli#71]
When displaying a maintenance period, the "Dayweek" listing does not show a "0" for the last day of week.  For example with a schedule of maintenance:
Every M, T, W, T ,F, Sa, Su will appear as 111111111111 (Correct).
If I was to remove Sunday from the schedule (Every M, T, W, T ,F, Sa) it appears as 111111, not having a 0 for Sunday

**Comment by paalbra** [comment]
I believe you might have mixed months and week days (you got twelve "1"s), but there is an issue with missing 0 padding. Both months and week days has this issue.
