### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by fullv2** [usit-gd/zabbix-cli#72]
Hello, 

I get an SSL error when I run some commands.
[ERROR]:  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

I configured my zabbix to run under HTTPS and the init runs with 
"zabbix-cli-init --zabbix-url https://XXX"

any idea?

**Comment by tipruzs** [comment]
Hi, same issue here. we run zabbix with self signed certificate. Is there any way to disable the ssl verification?

**Comment by rafaelma** [comment]
This is not difficult to fix.

By default the request.session.verify parameter is true, this activate SSL verification and the request will fail if one is using e.g. a self signed certificates.

The fix will be to define a session_ssl_verify parameter in the configuration file with true es default value. It will be possible to disable ssl verification by setting this parameter to false. It will also be possible to use self signed certificates by setting this parameter to the path of a CA_BUNDLE file or directory with certificates of trusted CAs.

This has to be done to implement this:

* Update default configuration file with new parameter.
* Update zabbix_cli/config.py with the new parameter (default value: true)
* Update zabbix_cli/cli.php, self.zapi.session.verify = True has to be changed to the parameter defined in zabnix_cli/config.php

Ref: http://docs.python-requests.org/en/master/user/advanced/

**Comment by lmgray** [comment]
The following will avoid insecure warnings on every request:

```
./zabbix_cli/cli.py:import urllib3
./zabbix_cli/cli.py:            urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

**Comment by ChuckB0ris** [comment]
Hello,

Any updates on this? I still heaven't managed to fix this, what exactly do I need to modify?

Thanks,
Chuck

**Comment by paalbra** [comment]
09c6095 allows you to set `cert_verify` in the `zabbix_api` config section. This will be passed to the requests library.

This allows you to configure a path to a CA bundle or set verification it to OFF/False.

Setting it to OFF/False will emit warnings. You could avoid these by using the `PYTHONWARNINGS` environment variable like so: `PYTHONWARNINGS="ignore" zabbix-cli`, but I would recommend that you use a proper certificate.

I assume that this commit will be present in a 2.1 release of zabbix-cli
